### PR TITLE
Added dynamic description of navigation endpoints

### PR DESCRIPTION
**Pull request by prakashsagadevan**
This commit added the dynamic description of navigation endpoints instead of hard-coded description("Get related ...").

### CODE REVIEW

**Comment by ralfhandl** [comment]
Hi @prakashsagadevan, thanks for the contribution.

Unfortunately I cannot merge it as is as:
1. Navigation property bindings cannot be annotated, [the `<NavigationPropertyBinding>` element does not allow child nodes](http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/cs01/odata-csdl-xml-v4.01-cs01.html#sec_NavigationPropertyBinding). You can verify this  with a schema-aware editor/validator using the XML schemas [edmx.xsd](https://github.com/oasis-tcs/odata-csdl-schemas/blob/master/schemas/edmx.xsd) and [edm.xsd](https://github.com/oasis-tcs/odata-csdl-schemas/blob/master/schemas/edm.xsd).

2. The OData TC is still discussing how to provide operation descriptions, `Description` annotations with a specific qualifier are only one of the discussed options.

3. The pull request does not contain an example that demonstrates how/whether the extended transformation works.

Thanks
Ralf

**Comment by prakashsagadevan** [comment]
Hi @ralfhandl 

Thanks for your comments. Please find my inline comments.

Thanks,
Prakash Sagadevan

> Hi @prakashsagadevan, thanks for the contribution.
> 
> Unfortunately I cannot merge it as is as:
> 
> 1. Navigation property bindings cannot be annotated, [the `<NavigationPropertyBinding>` element does not allow child nodes](http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/cs01/odata-csdl-xml-v4.01-cs01.html#sec_NavigationPropertyBinding). You can verify this  with a schema-aware editor/validator using the XML schemas [edmx.xsd](https://github.com/oasis-tcs/odata-csdl-schemas/blob/master/schemas/edmx.xsd) and [edm.xsd](https://github.com/oasis-tcs/odata-csdl-schemas/blob/master/schemas/edm.xsd).

I have updated NavigationProperty instead of NavigationPropertyBinding element for dynamic description. Please find the latest commit with the changes.

> 2. The OData TC is still discussing how to provide operation descriptions, `Description` annotations with a specific qualifier are only one of the discussed options.

I am looking forward for those changes. Can you please check the updated changes and let me know your thoughts?

> 3. The pull request does not contain an example that demonstrates how/whether the extended transformation works.

I have updated the ExampleService.xml Odata to demonstrate the transformation work. Can you please take a look at the ExampleService.xml and ExampleService.openapi3.json files? 

> 
> Thanks
> Ralf

**Comment by ralfhandl** [comment]
Hi @prakashsagadevan 

I suggest that you also add a `Core.LongDescription` to the navigation property just to see that it is also picked up.

Then please use the qualifier `Query` to be in sync with the other experimental  code. The description of the GET operation will usually differ from the description of the navigation property itself.

Finally why limit this to GET, the latest transformation also generates POST for collection-valued navigation properties, and there we'd want the `Create`-qualified description.

Thanks in advance
Ralf

**Comment by prakashsagadevan** [comment]
Hi @ralfhandl 

I have updated OpenAPI XSL file based on your comments. Please find my inline comments.

Thanks,
Prakash Sagadevan

> Hi @prakashsagadevan
> 
> I suggest that you also add a `Core.LongDescription` to the navigation property just to see that it is also picked up.

I have checked the navigation property with a long description and it is working as excepted. Please find examples in ExampleService.xml and ExampleService.openapi3.json files.
> 
> Then please use the qualifier `Query` to be in sync with the other experimental code. The description of the GET operation will usually differ from the description of the navigation property itself.

Changed OpenAPI XSL file to use qualifier as 'Query' in the GET Method.
> 
> Finally why limit this to GET, the latest transformation also generates POST for collection-valued navigation properties, and there we'd want the `Create`-qualified description.

I have updated POST method collection-valued navigation properties for dynamic description. Please find the latest commit with the changes.
> 
> Thanks in advance
> Ralf

**Comment by prakashsagadevan** [comment]
Hi @ralfhandl 

Can you please check the latest commit and merge the pull request if you are fine with the changes?

Thanks,
Prakash Sagadevan

**Comment by ralfhandl** [comment]
@prakashsagadevan I'll wait with merging until we've decided in the OData TC whether we want to use the approach with qualifiers on descriptions or rather use some other approach.

**Comment by ralfhandl** [comment]
Hi @prakashsagadevan,

Operation descriptions can now be added as described in https://issues.oasis-open.org/browse/ODATA-1264.

See https://github.com/oasis-tcs/odata-openapi/commit/b2d4f886aa4e962af8482e07b580398dfad1e2c8 for examples on how to set summary and description for individual operations along navigation properties.

**Pull request closed without merging**
